version: '3.0'

services:
  grafana:
    container_name: 'imageine-image-panel'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    ports:
      - 3050:3000/tcp
    volumes:
      - /home/dbal/plugins:/var/lib/grafana/plugins
      - ./dist:/var/lib/grafana/plugins/imageine-image-panel
      - ./provisioning:/etc/grafana/provisioning
